### ISSUE TITLE
Labels Out Of Order After Creating New Task

### ISSUE THREAD

**Issue by Transigent** [opencv/cvat#2636]
### My actions before raising this issue
- [ X ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ X ] Searched [past issues](/issues)

### Expected Behaviour
I want to use the same Labels in the same order as I have used in all the other Tasks I have created. I copy them from an existing Task but when the new Task is created they are out of order. I expect that they should be in the same order I entered them.

### Current Behaviour
I have previously annotated a number of images in tasks for an Object Recognition project. I want to be able to copy the Labels from an existing Task so when I start annotation of images they are in the same order, I am accustomed to the order of the Labels and I know where they are in the Labels list when I search for them. I have arranged them so that the most common are at the start of the list so I don't have to scroll to find them.

My other and more pressing concern is that with the Labels out of order, when I export to Yolo 1.1 format I might end up having different numbers representing the labels, which means they wont align with the Labels from the other Tasks. ie. Label1 might not correspond to '0' like it was for the other Tasks.

The problem is when I copy the Labels from a previous Task, and paste them into a new Task, or even when pasting in a manually generated list, they are out of order.

### Possible Solution
Nothing I have tried will correct the order of the Labels.

### Steps to Reproduce (for bugs)
I create a new Task and paste in JSON for the labels in the order I need them. Normally I would hit the Copy button from an existing Task but in this case I will just paste in the JSON [from this file](http://filestore1.tk/storage/LabelsJSON.txt). (I tried to enter it as code in this fault report but it would not format properly)

Labels have been entered via RAW tab, all looks normal

![Labels have been entered via RAW tab, all looks normal](http://filestore1.tk/storage/1LabelsEntered.jpg)

I click on the Constructor tab and it looks normal there too, all 14 labels are in correct order
![I click on the Constructor tab and it looks normal there too, all 14 labels are in correct order](http://filestore1.tk/storage/2LabelsShowOK.jpg)

Then I click Submit and open the Task and suddenly all the labels are in the wrong order
![](http://filestore1.tk/storage/3OpenedTaskAndAllLabelsAreWrong.jpg)

If I click on RAW they are in the wrong order there too
![](http://filestore1.tk/storage/4LabelsinJSONareWrongToo.jpg)

So I copy the JSON again and paste it in the RAW tab and click Done.
![](http://filestore1.tk/storage/5TryToPasteInCorrectJSONAgain.jpg)

No change on the Constructor or RAW tabs, still wrong order??
![](http://filestore1.tk/storage/6ChangesAreIgnored.jpg)

I did an Export As Dataset -> to CVAT for Images 1.1 and in the exported Zip the annotations file [looks like this](http://filestore1.tk/storage/annotations.xml)  (the order is correct in the xml file) 

I thought it might be a problem with the sort order but I added another Label called Label15 by copying and pasting a section into the RAW JSON and it just appeared at the end after all the others, so its not that. The edit took, so the JSON can apparently be edited but pasting in the raw JSON in the correct order again doesn't help at all.

### Context

- Git hash commit (`git log -1`):  
- Docker version `docker version` (e.g. Docker 17.0.05):   **Docker Engine Version  v20.10.0**
- Are you using Docker Swarm or Kubernetes?  :  **No**
- Operating System and version (e.g. Linux, Windows, MacOS):  **WINDOWS 10 Pro Build 20H2**
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:

**CVAT About box details:
Server version: 1.2
Core version: 3.8.0
Canvas version: 2.1.3
UI version: 1.9.13**

Any thoughts? This is driving me up the wall. Thanks for any advice.

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
Looks like there is an alphabetical sorting happens during task creation.

BTW, labels can only be added after task creation, they can't be modified.

**Comment by Transigent** [comment]
Here is an easily reproduceable way to exhibit the problem (for me):

1) Create a new task
2) Add some labels by [opening this file](http://filestore1.tk/storage/LabelsJSON.txt) and copying and pasting in the JSON into the RAW tab, replacing the brackets that are there, and press Done.  
3) Click the Constructor tab and confirm the labels are in order
4) Give the task a name, say "Test" and I dont know if you are required to, but I dragged and dropped an image file. 
5) Click submit
6) On the menu along the top press Tasks. The new task will appear.
7) Click the Open button next to the new task. The task will appear like this:
![](http://filestore1.tk/storage/7-TaskCreated.jpg)

8) OK, now again click the Tasks link at the top, but this time instead of left-clicking the Open button, right click it and "Open link in a new tab". In any other application the behavior will produce the same result.
9) Look at the labels now, they are in the wrong order. And that might be the end of it, except that if you click on the Job below, and start working on it, in the list of labels they are also in the wrong order!?

![](http://filestore1.tk/storage/8-LabelsAreInWrongOrder.jpg)


![](http://filestore1.tk/storage/9-PulldownListIsWrongToo.jpg)



> Looks like there is an alphabetical sorting happens during task creation.
> 
> BTW, labels can only be added after task creation, they can't be modified.

OK thanks for the tip about the labels.

**Comment by niniack** [comment]
Is there any workaround for this?

**Comment by nmanovic** [comment]
It is better now. But when I have created a task labels were in the reverse order. Looks like a bug.

**Comment by bsekachev** [comment]
@ActiveChooN 
Don't you think it was fixed by your PR? #3987

**Comment by klakhov** [comment]
It seems issue was fixed, feel free to reopen if not.

**Comment by harshraj22** [comment]
@bsekachev Should all the labels be added in one go ? or the ordering is expected to work even if labels are added in batches. eg. I add 3 labels via constructor tab and save them. and then wait a while, and then add labels again.

**Comment by bsekachev** [comment]
@harshraj22 

Sounds logically if order keeps even when you append labels later..

**Comment by FraidOfWater** [comment]
Still happens for backup export and import. But it's a feature, this way you can actually reorder your labels by "cheating" the system. You first relabel your label names with an index  1. Label1, 2. Label2, then you export, import, and tada, you have reordered the labels cvat won't let you normally reorder.
