### ISSUE TITLE
Run YOLOv7 model, CPU memory usage increased significantly.

### ISSUE THREAD

**Issue by seasenzzr000** [opencv/cvat#6793]
hi，CVAT Scientists.I am a beginner of computer.Encountered some problems in CVAT deployment model.I followed the instructions provided to deploy CVAT.And deploy the automatic annotation.But I found that when using YOLOv7 run without using the GPU, CPU memory value added from 70% to 1400%.
How do I check which GPU or CPU is used to run YOLOv7?And, how to solve it?

Environment
docker：24.0.2
python：3.6.9
cvat server：2.6.0
GPU：NVIDIA RTX 3090

Step：
```shell
git clone https://github.com/opencv/cvat
``` 
```shell
docker compose up -d
``` 
 ```shell
docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
``` 
```shell
wget https://github.com/nuclio/nuclio/releases/download/<version>/nuctl-<version>-linux-amd64
``` 
```shell
sudo chmod +x nuctl-<version>-linux-amd64
sudo ln -sf $(pwd)/nuctl-<version>-linux-amd64 /usr/local/bin/nuctl
``` 
```shell
./serverless/deploy_cpu.sh serverless/openvino/dextr
./serverless/deploy_cpu.sh serverless/openvino/omz/public/yolo-v3-tf
``` 
```shell
nuctl deploy --project-name cvat \
  --path serverless/tensorflow/matterport/mask_rcnn/nuclio \
  --platform local --base-image tensorflow/tensorflow:1.15.5-gpu-py3 \
  --desc "GPU based implementation of Mask RCNN on Python 3, Keras, and TensorFlow." \
  --image cvat/tf.matterport.mask_rcnn_gpu \
  --triggers '{"myHttpTrigger": {"maxWorkers": 1}}' \
  --resource-limit nvidia.com/gpu=1
``` 
```shell
cd serverless && ./deploy_gpu.sh pytorch/facebookresearch/sam/nuclio/
``` 
```shell
cd serverless && ./deploy_cpu.sh onnx/WongKinYiu/yolov7/nuclio/
``` 

Set SharePath
```shell
docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml -f docker-compose.override.yml up -d
``` 
 Everything seems normal，However, when I ran the YOLOv7 model, I ran nvidia-smi on the server and found that the video memory did not change significantly, but the CPU memory exploded.
 I don't know how to check it.And, if found to be wrong, how do I change it.

```shell
nuctl get function
``` 
```shell
  NAMESPACE |              NAME              | PROJECT | STATE | REPLICAS | NODE PORT  
  nuclio    | onnx-wongkinyiu-yolov7         | cvat    | ready | 1/1      |     32777  
  nuclio    | openvino-dextr                 | cvat    | ready | 1/1      |     32773  
  nuclio    | openvino-omz-public-yolo-v3-tf | cvat    | ready | 1/1      |     32774  
  nuclio    | pth-facebookresearch-sam-vit-h | cvat    | ready | 1/1      |     32776  
  nuclio    | tf-matterport-mask-rcnn        | cvat    | ready | 1/1      |     32775  

``` 

```shell
root@cvat-gpu:/opt/cvat# docker exec -it nuclio-nuclio-pth-facebookresearch-sam-vit-h /bin/bash
nvidia-smi
pythonroot@3304ec5efe58:/opt/nuclio/sam# nvidia-smi
Mon Sep  4 06:39:12 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.05              Driver Version: 535.86.05    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:02:00.0 Off |                  N/A |
| 48%   28C    P8              28W / 350W |   7978MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
root@3304ec5efe58:/opt/nuclio/sam# python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda.device_count()
1
>>> 

``` 
```shell
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                     
16672 root      20   0 4456268 547180   6156 R  1160  0.6   5952:43 python3                                                                                                                                                                     
24704 core0203  20   0 4925096 395060  16480 S  34.5  0.4  64:00.32 python3 
``` 

I don't know what to do, please help me.

**Comment by bsekachev** [comment]
@seasenzzr000 

> cd serverless && ./deploy_cpu.sh onnx/WongKinYiu/yolov7/nuclio/

You deployed Yolo v7 on CPU, it uses RAM.

**Comment by seasenzzr000** [comment]
> 

Sorry, I wrote it wrong, gpu is used during deployment.

```shell
cd serverless && ./deploy_gpu.sh onnx/WongKinYiu/yolov7/nuclio/
```

**Comment by bsekachev** [comment]
Did you try going to the container and printing nvidia-smi there to see processes using GPU?

For example:
```
docker exec -it nuclio-nuclio-pth-facebookresearch-sam-vit-h /bin/bash
nvidia-smi
```

**Comment by seasenzzr000** [comment]
> 您是否尝试进入容器并在那里打印 nvidia-smi 以查看使用 GPU 的进程？
> 
> 例如：
> 
> ```
> docker exec -it nuclio-nuclio-pth-facebookresearch-sam-vit-h /bin/bash
> nvidia-smi
> ```

I tried running SAM and YOLOv7 with CVAT and nothing happened to the GPU process inside the container
`root@3304ec5efe58:/opt/nuclio/sam# nvidia-smi -l`

```shell
Mon Sep  4 08:29:10 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.05              Driver Version: 535.86.05    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:02:00.0 Off |                  N/A |
| 48%   32C    P8              28W / 350W |   7978MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

``` 
This shows that I deployed on the CPU?Then what should I do?

**Comment by seasenzzr000** [comment]
Please help me, how to change CPU support to GPU support? @bsekachev thk~

**Comment by Petros626** [comment]
Hey @seasenzzr000 ,

I would do the folllowing:
1. delete all functions `nuctl delete function name_of_the_function`
2. follow the instructions here (https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/)
3. maybe that's it (be careful about the ports, when you build the functions)
(4). add port: 12345 (any number) before deploying with `deploy_gpu.sh`

**Comment by SpecLad** [comment]
@seasenzzr000 Could you try again with the version of `function-gpu.yaml` from this pull request: #6940?

**Comment by OB1kanOB** [comment]
> @seasenzzr000 Could you try again with the version of `function-gpu.yaml` from this pull request: #6940?

Hi @SpecLad,
I tried with the PR #6940 changes i.e. using onnxruntime-gpu but I still see only CPU usage for YOLOv7
nvidia-smi doesn't show any GPU usage
