### ISSUE TITLE
Helm can't install with analytics.enabled false

### ISSUE THREAD

**Issue by hannatao** [opencv/cvat#7507]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. set analytics.enabled to false in values.yaml 
2. run helm install

### Expected Behavior

Install without analytics

### Possible Solution

This problem doesn't exist in v2.8.0

### Context

I got this error
`Error: template: cvat/charts/redis/templates/master/service.yaml:12:14: executing "cvat/charts/redis/templates/master/service.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: cvat/charts/postgresql/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: cvat/charts/postgresql/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name`

**Comment by hannatao** [comment]
In addition, my k8s version is v1.20.15, helm version is v3.6.3.

**Comment by abhi-bhatra** [comment]
Hi @nmanovic I found the fix of this issue. It is coming due to compatibility of *common* chart dependency between Postgres and Redis. I have installed common chart as a separate sub chart. This will possibly fix the issue. I have tried running Helm with analytics enabled and disabled. It is fixed !

**Comment by sriramsowmithri9807** [comment]
@hannatao bro you need to go to the last updatted version of  k8s version is v1.20.15, helm version is v3.6.3, of these, hopefully you will get the expected output!!


Reason: The latest version contains some bugs thats the main reason why you are not getting the output.

**Comment by koolvn** [comment]
This is still an issue. 
k8s v1.33.1
helm v3.17.3
cvat v2.38.0

I've disabled analytics. But had to keep clickhouse enabled and do a tiny hack like on the screenshot

<img width="680" alt="Image" src="https://github.com/user-attachments/assets/7c4cbdac-f4fb-4509-b82e-331a245fc191" />

Had to change two files to make cvat start - `cvat/helm-chart/templates/analytics/cvat-analytics-secret.yml` and `cvat/helm-chart/templates/analytics/clickhouse/secret.yml`

**Comment by azhavoro** [comment]
The root cause is #7507; let's leave only one issue open.

**Comment by kubasrna** [comment]
Hi guys, any update on this? I still see the same issue in version 2.45.0.
